<a href="https://colab.research.google.com/github/HelenDiMo/Bootcamp-F5/blob/main/trabajando_con_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("✅ NumPy importado correctamente")
print(f"Versión de NumPy: {np.__version__}")

✅ NumPy importado correctamente
Versión de NumPy: 2.0.2


In [ ]:
import numpy as np

#Listas

a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

array_a = np.array(a)
array_b = np.array(b)

# Sumatorio
print(array_a + array_b)


# Características
print("Tipo de objeto", type(a))
print("Tipo de objeto", type(array_a))
print("Tipo de datos", array_a.dtype)
print("Forma del array_a", array_a.shape)
print("Número tortal de elementos en el array_a_: ", len(array_a))


[ 7  9 11 13 15]
Tipo de objeto <class 'list'>
Tipo de objeto <class 'numpy.ndarray'>
Tipo de datos int64
Forma del array_a (5,)
Número tortal de elementos en el array_a_:  5


In [ ]:
# Creacion de un array en 2D

ar2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(ar2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Array de solo ceros

ar0 = np.zeros(5)

print(ar0)

[0. 0. 0. 0. 0.]


In [ ]:
# Array solo de 1

ar1 = np.ones((4, 2))

print(ar1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Con rango (como range() de Python, pero devuelve un array)

print(ar2)
print()
np.arange(1, 10, 2) # Start, Stop, Cada cuanto queremos que avance

[[1 2 3 4]
 [5 6 7 8]]



array([1, 3, 5, 7, 9])

In [ ]:
# Random - Crea un array de 2 filas y 3 columnas y selecciona números random del 0 al 1

np.random.random((2, 3))

array([[0.84365165, 0.66933465, 0.01369793],
       [0.04896929, 0.86807894, 0.84998967]])

In [ ]:
# Full

arfull = np.full(4, 10)
print(arfull)

[10 10 10 10]


In [ ]:
# Con valoreas equiespaciados - linspace

arlin = np.linspace(0, 100, 5)
print(arlin)

[  0.  25.  50.  75. 100.]


In [ ]:
# EJERCICIO

ar4 = np.array([[1, 5, 8, 9], [5, 8, 9, 11]])

print(ar4)
print()
print("==============================")
print()
print("Shape: ", ar4.shape)
print("Size: ", ar4.size)
print("Dimension: ", ar4.ndim)
print("Tipo de dato: ", ar4.dtype)

[[ 1  5  8  9]
 [ 5  8  9 11]]


Shape:  (2, 4)
Size:  8
Dimension:  2
Tipo de dato:  int64


In [ ]:
# Bloque 3 - Operaciones

In [ ]:
a = np.array([1, 2, 3, 4])
a

# Operaciopnes básicas + - * /:

a + 5
a - 10


array([-9, -8, -7, -6])

In [ ]:
# Acceder a elementos (igual que en las listas)
# Los índices empiezan en 0

b = np.array([1, 2, 3, 4, 5])
b

print(b[0]) # Determinada y ultima posicion
print(b[4]) # Última posicion
print(b[-1]) # Última posicion


1
5
5


In [ ]:
c = np.array([[1, 5, 8, 9], [5, 8, 9, 11]])

print(c[0,0])

1


VECTORES

In [ ]:
# VECTORES

ventas = np.array([100, 200, 300])
costes = np.array([50, 80, 100])
ventas, costes

(array([100, 200, 300]), array([ 50,  80, 100]))

In [ ]:
beneficio = ventas - costes
beneficio

array([ 50, 120, 200])

MATRICES

In [ ]:
datos = np.array([
    [100, 50],
    [200, 80],
    [300, 100]
])
datos



array([[100,  50],
       [200,  80],
       [300, 100]])

In [ ]:
datos.shape

(3, 2)

In [ ]:
datos * 2

array([[200, 100],
       [400, 160],
       [600, 200]])

In [ ]:
import numpy as np

# CREAR EL PRIMER ARRAY
datos = np.array([10, 20, 30, 40, 50])
datos




array([10, 20, 30, 40, 50])

In [ ]:
# VALOR:    10   20  30  40  50
# POSICION:  0    1   2   3   4

datos[0:3]

array([10, 20, 30])

In [ ]:
# ¿Qué saldrá?
datos[1:4]

array([20, 30, 40])

In [ ]:
matriz = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

matriz

#

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# Extraer una fila - Las filas se cuentan desde el cero
print(matriz[0])
print(matriz[1])
print(matriz[2])

[10 20 30]
[40 50 60]
[70 80 90]


In [ ]:
# Extraer una columna - los : nos dice "todos los elementos de la columna" y el 1 es el indice que dia
print(matriz[:,1])
print(matriz[:,0])

[20 50 80]
[10 40 70]


In [ ]:
matriz[0:3,2] # Investigar esto a ver

array([30, 60, 90])

In [ ]:
# SOLO QUEREMOS MOSTRAR LOS VALORES 10, 20 // 40, 50
matriz[0:2, 0:3]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

CREACION DE CAFETERIA DIGITAL

In [ ]:
# CREACION DE LA MATRIZ
# [cafés vendidos, croissants vendidos]

ventas = np.array([
    [10,5],#lunes
    [15,8],#martes
    [12,6],#miercoles
    [20,12],#jueves
    [25,15],#viernes
])

print("Nuestra tabla de ventas: ")
print(ventas)

Nuestra tabla de ventas: 
[[10  5]
 [15  8]
 [12  6]
 [20 12]
 [25 15]]


In [ ]:
ventas[0]
croissants_vendidos = ventas[:,1]
print(croissants_vendidos)


[ 5  8  6 12 15]


In [ ]:
ventas_inicio_semana = ventas[0:2, :]
print(ventas_inicio_semana)

[[10  5]
 [15  8]]


In [ ]:
ventas_ajuste = ventas + 0.5
print("Precios ajustados: ")
print(ventas_ajuste)

Precios ajustados: 
[[10.5  5.5]
 [15.5  8.5]
 [12.5  6.5]
 [20.5 12.5]
 [25.5 15.5]]


In [ ]:
# BROADCASTING

a = np.array([1, 2, 3])
b = 2

result = a + b
print(result)
# suma 2 a cada elemento de la fila

[3 4 5]


In [ ]:
arr = np.array([1, 2, 3])
matriz = np.array([[1, 2, 3], [4, 5, 6]])

result = arr + matriz
print(result)


[[2 4 6]
 [5 7 9]]


In [ ]:
#2 cafes + 1 = 5€
#1 cafe + 1 croissant = 3€

#Código Sistemas Lineales
# A array de lo que compramos
A = np.array([
    [2, 1],#Lunes
    [1, 1] #Martes
])
#De lo que se paga
B = np.array([5, 3])

solucion = np.linalg.solve(A, B)
print(solucion)
#

[2. 1.]


08/04/2026

In [3]:
import numpy as np
from scipy import stats
print("✅ Librerías cargadas correctamente")
print(f"   numpy  {np.__version__}")

✅ Librerías cargadas correctamente
   numpy  2.0.2


In [6]:
# Generamos datos de salarios de una empresa pequeña
# 10 empleados normales y 1 persona que gana mucho (Outlier)
lista = [1200, 1300, 1100, 1400, 1250, 1350, 1150,1200, 1300, 1200, 2500]
salarios = np.array(lista)
print(f"Salarios de la oficina: {salarios}")
print(salarios)
salarios
print("Size: ", salarios.size)

Salarios de la oficina: [1200 1300 1100 1400 1250 1350 1150 1200 1300 1200 2500]
[1200 1300 1100 1400 1250 1350 1150 1200 1300 1200 2500]
Size:  11
