<a href="https://colab.research.google.com/github/HelenDiMo/Bootcamp-F5/blob/main/trabajando_con_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
print("✅ NumPy importado correctamente")
print(f"Versión de NumPy: {np.__version__}")

✅ NumPy importado correctamente
Versión de NumPy: 2.0.2


In [20]:
import numpy as np

#Listas

a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

array_a = np.array(a)
array_b = np.array(b)

# Sumatorio
print(array_a + array_b)


# Características
print("Tipo de objeto", type(a))
print("Tipo de objeto", type(array_a))
print("Tipo de datos", array_a.dtype)
print("Forma del array_a", array_a.shape)
print("Número tortal de elementos en el array_a_: ", len(array_a))


[ 7  9 11 13 15]
Tipo de objeto <class 'list'>
Tipo de objeto <class 'numpy.ndarray'>
Tipo de datos int64
Forma del array_a (5,)
Número tortal de elementos en el array_a_:  5


In [22]:
# Creacion de un array en 2D

ar2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(ar2)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
#Array de solo ceros

ar0 = np.zeros(5)

print(ar0)

[0. 0. 0. 0. 0.]


In [26]:
# Array solo de 1

ar1 = np.ones((4, 2))

print(ar1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [30]:
# Con rango (como range() de Python, pero devuelve un array)

print(ar2)
print()
np.arange(1, 10, 2) # Start, Stop, Cada cuanto queremos que avance

[[1 2 3 4]
 [5 6 7 8]]



array([1, 3, 5, 7, 9])

In [31]:
# Random - Crea un array de 2 filas y 3 columnas y selecciona números random del 0 al 1

np.random.random((2, 3))

array([[0.84365165, 0.66933465, 0.01369793],
       [0.04896929, 0.86807894, 0.84998967]])

In [36]:
# Full

arfull = np.full(4, 10)
print(arfull)

[10 10 10 10]
